AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: CF Stack for eks
Resources:
  EKSRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: eks-role-sb
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
  SBEKSVpc:
    Type: AWS::Serverless::Application
    Properties:
      Location: vpc-template.yaml
    Metadata:
      SamResourceId: SBEKSVpc
  SBEKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: SBEKSC
      Version: "1.20"
      RoleArn: !GetAtt EKSRole.Arn
      ResourcesVpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: SecurityGroups
        SubnetIds: !Split 
          - ","
          - Fn::ImportValue:
              SubnetIds          
        EndpointPublicAccess: false
        EndpointPrivateAccess: true
      Logging:
        ClusterLogging:
          EnabledTypes:
            - Type: api
            - Type: audit

Outputs:
  EksRole:
    Description: EKS Role Arn
    Value: !GetAtt EKSRole.Arn
